[versions]
agp = "8.8.2"
billing = "8.2.0"
flexbox = "3.0.0"
gson = "2.10.1"
guava = "32.1.3-android"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
constraintlayout = "2.2.1"
lifecycleLivedataKtx = "2.9.1"
lifecycleViewmodelKtx = "2.9.1"
materialCalendarview = "2.0.1"
mpandroidchart = "v3.1.0"
navigationFragment = "2.9.0"
navigationUi = "2.9.0"
picasso = "2.8"
playServicesAds = "24.9.0"
recyclerview = "1.4.0"
roomRuntime = "2.6.1"
lombok = "1.18.36"
lottie = "0.12.5"
commonsLang3 = "3.12.0"
exp4j = "0.4.8"
preference = "1.2.1"
workRuntime = "2.10.0"
activity = "1.10.1"
legacySupportV4 = "1.0.0"
colorpickerview = "2.3.0"

[libraries]
billing = { module = "com.android.billingclient:billing", version.ref = "billing" }
colorpickerview = { module = "com.github.skydoves:colorpickerview", version.ref = "colorpickerview" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
material-calendarview = { module = "com.github.prolificinteractive:material-calendarview", version.ref = "materialCalendarview" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
lottie = { module = "com.github.LottieFiles:dotlottie-android", version.ref = "lottie" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3" }
exp4j = { module = "net.objecthunter:exp4j", version.ref = "exp4j" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }

[plugins]
android-application = { id = "com.android.library", version.ref = "agp" }
com-android-application = { id = "com.android.application", version.ref = "agp" }